steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'warsaw-docker.pkg.dev/rss-citacka/fusion-repo/fusion:latest', '.']
images:
- 'warsaw-docker.pkg.dev/rss-citacka/fusion-repo/fusion:latest'
options:
  logging: 'CLOUD_LOGGING_ONLY'  # Use Cloud Logging for build logs
